# docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]