"""initial schema

Revision ID: 5089dac88e82
Revises:
Create Date: 2025-10-14 23:00:02.367560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5089dac88e82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_history',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('invested_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gross_invested', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross_withdrawn', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), sa.Computed('total_value - invested_value', ), nullable=True),
    sa.Column('total_pnl_pct', sa.Numeric(precision=20, scale=8), sa.Computed('CASE WHEN invested_value <> 0 THEN ((total_value - invested_value) / invested_value) * 100 ELSE 0 END', ), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('tickers',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ticker'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('positions',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross_invested', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross_withdrawn', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    op.create_table('prices',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ),
    sa.PrimaryKeyConstraint('id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('prices')
    op.drop_table('positions')
    op.drop_table('tickers')
    op.drop_table('portfolio_history')
    # ### end Alembic commands ###
